# Generated by Django 4.1.4 on 2023-01-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('semester', models.IntegerField(primary_key=True, serialize=False)),
                ('course1', models.CharField(max_length=100)),
                ('course2', models.CharField(max_length=100)),
                ('course3', models.CharField(max_length=100)),
                ('course4', models.CharField(max_length=100)),
                ('course5', models.CharField(max_length=100)),
                ('course6', models.CharField(max_length=100)),
            ],
        ),
    ]
