# Generated by Django 4.1.4 on 2023-01-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_courses_course1_alter_courses_course2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course5',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course6',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
