# Generated by Django 4.1.4 on 2023-01-04 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_courses_course1_alter_courses_course2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
