# Generated by Django 4.1.4 on 2023-01-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0004_delete_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('sem', models.IntegerField(primary_key=True, serialize=False)),
                ('crs_id', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=100)),
            ],
        ),
    ]
