# Generated by Django 4.1.4 on 2023-01-04 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
