# Generated by Django 4.1.4 on 2023-01-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0006_delete_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.IntegerField()),
                ('crs_id', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=100)),
            ],
        ),
    ]
