# Generated by Django 4.1.4 on 2023-01-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=100)),
                ('course1', models.CharField(max_length=100)),
                ('course2', models.CharField(max_length=100)),
                ('course3', models.CharField(max_length=100)),
                ('course4', models.CharField(max_length=100)),
                ('course5', models.CharField(max_length=100)),
                ('course6', models.CharField(max_length=100)),
            ],
        ),
    ]
