# Generated by Django 4.1.4 on 2023-01-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='id',
        ),
        migrations.AlterField(
            model_name='courses',
            name='semester',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
