# Generated by Django 4.1.4 on 2023-01-02 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_courses_id_alter_courses_semester'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
