# Generated by Django 4.1.4 on 2023-01-04 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_delete_courses'),
        ('authentication', '0005_alter_teacherprofile_user'),
    ]

    operations = [
    ]
