# Generated by Django 4.1.4 on 2023-01-04 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_merge_20230103_1851'),
        ('authentication', '0006_merge_20230104_2108'),
    ]

    operations = [
    ]
