# Generated by Django 4.1.4 on 2023-01-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crs_id', models.CharField(max_length=20)),
                ('qb_pdf', models.FileField(upload_to='../upload/media/')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crs_id', models.CharField(max_length=20)),
                ('links', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crs_id', models.CharField(max_length=20)),
                ('syb_pdf', models.FileField(upload_to='../upload/media/')),
            ],
        ),
    ]
