# Generated by Django 4.1.4 on 2023-01-08 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_alter_qb_qb_pdf_alter_syllabus_syb_pdf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QB',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='Syllabus',
        ),
    ]
