# Generated by Django 4.1.4 on 2023-01-07 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UploadFiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyFileUpload',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='file_name',
            new_name='crs_id',
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='my_file',
            new_name='notes_pdf',
        ),
    ]
