# Generated by Django 4.1.4 on 2023-01-07 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UploadFiles', '0002_rename_myfileupload_notes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='crs_id',
            new_name='file_name',
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='notes_pdf',
            new_name='my_file',
        ),
    ]
