# Generated by Django 4.1.4 on 2023-01-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadFiles', '0003_rename_crs_id_notes_file_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='sylabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=50)),
                ('my_file', models.FileField(upload_to='')),
            ],
        ),
    ]
