# Generated by Django 4.1.4 on 2023-01-08 06:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadFiles', '0005_quiz_alter_notes_my_file_alter_sylabus_my_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='my_file',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'pptx'])]),
        ),
    ]
