# Generated by Django 4.1.4 on 2023-01-08 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UploadFiles', '0006_alter_notes_my_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='quiz',
        ),
    ]
