# Generated by Django 4.1.4 on 2023-01-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadFiles', '0009_notes_course_name_sylabus_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sylabus',
            name='my_file',
            field=models.FileField(upload_to=''),
        ),
    ]
